name: Install Howebrew in container
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        apt-get -y update
        # https://docs.brew.sh/Homebrew-on-Linux#requirements
        apt-get -y install --no-install-recommends curl ca-certificates git gcc
        curl -fsSLo /tmp/install.sh https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
        /bin/bash /tmp/install.sh

        # Add `brew` to PATH
        # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#adding-a-system-path
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        # Set other `brew` vars to fix bottle installation problem
        # https://github.com/Homebrew/discussions/discussions/2713
        /home/linuxbrew/.linuxbrew/bin/brew shellenv
        ls -la /home/linuxbrew/.linuxbrew
        echo "HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew" >> $GITHUB_ENV
        echo "HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar" >> $GITHUB_ENV
        echo "HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew" >> $GITHUB_ENV
